name: Continuous Integration Tests (pytest)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install package and dependencies
        run: |
          conda install pygraphviz
          pip install -e .
          pip install pytest pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov=causal_testing
      - name: Determine coverage
        run: |
          coverage xml
      - name: Report coverage
        uses: codecov/codecov-action@v1