name: Containerise and Upload to DAFNI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build_and_upload:
    name: Docker Build
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      DAFNI_PARENT_ID: ${{ secrets.DAFNI_PARENT_ID }}
      DAFNI_USERNAME: ${{ secrets.DAFNI_USERNAME }}
      DAFNI_PASSWORD: ${{ secrets.DAFNI_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set CTF_VERSION and VERSION
        run: |
          TAG=${{ github.event.release.tag_name }}
          CTF_VERSION="$TAG"
          VERSION=$(echo "$TAG" | sed 's/v//; s/\.[0-9]*$//')
          echo "CTF_VERSION=${CTF_VERSION}" >> $GITHUB_ENV
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Build the container
        run: |
          docker build -t ctf:VERSION -f ./dafni/Dockerfile .
          docker save ctf:VERSION  | gzip > ctf-${VERSION}.tar.gz

      - name: Install DAFNI-CLI and log in
        run: |
          python -m pip install dafni-cli
          dafni login

      - name: Upload to DAFNI
        run: |
          dafni upload model ./dafni/model_definition.yaml ctf-${{ env.VERSION }}.tar.gz --version-message "Version ${{ env.CTF_VERSION }}. Uploaded via Github." --parent-id ${DAFNI_PARENT_ID} -y
          dafni logout
