name: Containerise and Upload to DAFNI

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:

  build_and_upload:
    name: Docker Build
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      DAFNI_PARENT_ID: ${{ secrets.DAFNI_PARENT_ID }}
      DAFNI_USERNAME: ${{ secrets.DAFNI_USERNAME }}
      DAFNI_PASSWORD: ${{ secrets.DAFNI_PASSWORD }}
      CTF_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Build the container
        run: |
          docker build -t ctf:gh -f ./dafni/Dockerfile .
          docker save ctf:gh  | gzip > ctf-gh.tar.gz

      - name: Install DAFNI-CLI and log in
        run: |
          python -m pip install dafni-cli
          dafni login

      - name: Upload to DAFNI
        run: |
          dafni upload model ./dafni/model_definition.yaml ctf-gh.tar.gz --version-message "Version ${{ env.CTF_VERSION }}. Uploaded via Github." --parent-id ${DAFNI_PARENT_ID} -y
          dafni logout
